create tablespace APEX DATAFILE 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\APEX.DBF' SIZE 1200M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

create tablespace APEX_FILES DATAFILE 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\APEX_FILES.DBF' SIZE 300M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

@C:\Apex\apex\apexins APEX APEX_FILES temp /i/

@C:\Apex\apex\apex_rest_config.sql

alter user APEX_PUBLIC_USER ACCOUNT UNLOCK;
alter user APEX_PUBLIC_USER IDENTIFIED BY admin;

exec dbms_xdb.sethttpport(0);

@C:\Apex\apex\apxchpwd.sql